### ISSUE TITLE
Git Tools + Resharper causes VS to freeze every few seconds.

### ISSUE THREAD

**Issue by stucampbell** [yysun/git-tools#10]
I submitted a support request to Jetbrains saying that VS 2013 and 2015 were freezing every few seconds. They analysed the profiling snapshot I sent them and replied:

> All the time in the snapshot is taken by git integration into Visual Studio
>    `- F1SYS.VsGitToolsPackage.VsGitToolsService.timer_Tick()`
>    `- Microsoft.TeamFoundation.Git.CoreServices.QueuedActionLimiter.DeliverAction()`
>    There's no ReSharper code running in the snapshot.

I don't use the MS Git Provider - I only ever use Git Tools. This problem didn't occur with the old version (when it was called Git Source Control Provider).
I wish I had time to debug this myself but unfortunately I don't. Hopefully some other kind soul can solve this show stopper - it makes VS unusable .

**Comment by cyberium** [comment]
I can confirm this. I have only GitTools installed. I experienced some freeze.

**Comment by yysun** [comment]
OK, thanks. Will take a look.

**Comment by lee-elenbaas** [comment]
We experience the same issue as well - and it makes it impossible to use the extension

**Comment by p-mec** [comment]
Same here. VS becomes unusable while using this extension.

**Comment by stucampbell** [comment]
Hi @yysun Thanks for your efforts with this extension. Do you intend to continue developing it?

**Comment by Sucran** [comment]
the freeze happens every time when I edit the code, but this tool is fantastic and help me a lot, thank you.

**Comment by jzoss** [comment]
Hi all .. I'm the developer of the other [Git plugin](https://github.com/jzoss/Git-Source-Control-Provider)  forked from the original Git Source Control Provider.  @yysun I ran into this problem myself, and it was..less than fun to fix. It wicked complicated .. It has to do with thread contention.. You can read a bit about [here](https://github.com/jzoss/Git-Source-Control-Provider/issues/17#issuecomment-175773026) But I'm not sure how helpful it will be.. I'm willing to help out, though I am not sure what the path of least resistance would be.

**Comment by yysun** [comment]
Of course @jzoss. I really appreciated your help.The two projects share the
GitApi library, which I saw you made a lot improvements in GitScc. Perhaps
it is the start point to copy the improved library to Git Tools.
Also I think it's better to make you as project contributor than to have a
fork project.
