### ISSUE TITLE
Misleading info about file with both staged and unstaged modifications

### ISSUE THREAD

**Issue by brunoleos** [yysun/git-tools#14]
For a file with both staged and unstaged modifications, Git Changes shows one item for the file, with Modified status, which is misleading, because this status is shown for unstaged files, and Staged is shown for staged files.
Besides, the modifications shown at the Diff View are both from staged and unstaged changes.

I would be very useful for me if I could have two different items at the left pane for this case: 
* one with unstaged changes, marked as Modified, and wich shows at the Diff View the same as `git diff <file>`;
* the second with staged changes, marked as Staged, and which shows at the Diff View the same as `git diff --cached <file>`.

Hope this is not so difficult to implement.

A feature I'm really after is the ability to select lines to stage, as **git gui** does, known as _interactive staging_ (`git add -i`). Is it much difficult to implement something as the Visual Studio Merge, with checkboxes to select the modifications to stage?

**Comment by yysun** [comment]
When this project was started back in the time of VS 2008, one goal was to hide the concept of index/stage to make it easier for VS developers. Nowadays, more and more understand this concept and want to use it. Myself included.

I am thinking to make it into two modes: 
**Simple mode**: same as it as today, people can use it w/o bothering of staging
**Advance mode**: make two grids, one for staged changes; one for unstaged changes; also support staging/unstaging by file chunks in the diff view

**Comment by yysun** [comment]
Pushed the adv-mode branch. It has the advanced mode that displays two lists: unstaged changes and staged changes.  The second feature you asked is implemented this way: you can select lines start with + or - in diff view, and then click a button to stage/unstage/reset the selected changes.

**Comment by yysun** [comment]
Preview:
![advanced-mode](https://cloud.githubusercontent.com/assets/170547/23167224/81f4dfda-f811-11e6-899c-a747b726dc3a.png)

**Comment by brunoleos** [comment]
That's it. Thanks for the great work, man. 

I couldn't test this yet. Are you planning to update at the Marketplace? I'm not compiling from source.

**Comment by yysun** [comment]
2.0.0 is available in the marketplace.
