### ISSUE TITLE
Now,VS2019 is available, when can it be supported?

### ISSUE THREAD

**Issue by wxk0248** [yysun/git-tools#25]
The latest version only supports vs2017

**Comment by yysun** [comment]
Working on it

**Comment by bernd5** [comment]
I tried it myself. I changed your main Package to an AsyncPackage, the version number ranges and some other small things like Initialize to InitializeAsync.
After these changes I was able to compile the project and to install it in VS2019.
It just looked fine, but I can't find it in the menu, really strange. Do you have the same issues aswell?

**Comment by yysun** [comment]
I have not got that far yet. The codebase has stuffs support Visual Studio
back to 2008. I started creating a VS 2019 extension project and migrate
the package to AsyncPackage. If you want, you can create pull request. I
will merge and take a look.

**Comment by Matthewsre** [comment]
Glad to see this is being worked on. I dropped back down to VS2017 because I rely on the Git Changes window so much when getting ready to commit. Thanks for working on this!

**Comment by yysun** [comment]
Made the first build to the marketplace. Continue to research and fix the issues that the diff view is not highlighting.
