### ISSUE TITLE
How can i call  git consle window out?

### ISSUE THREAD

**Issue by lookforit** [yysun/git-tools#3]
Hi,

Excellent plugin for git users those who  using `Vs` at the same time , I must say !
I installed version `1.4` with  `VS2013`, and I failed to find the way to trigger `Git Console` function, which  was  described in the demo page.
By the way, I found  only 3 items above the `GITTOOlS` menu:
- Git Changes 
- Git Bash
- About 

Any help?

**Comment by yysun** [comment]
The git console is inside the Git Changes Window. 
![git console](http://yysun.github.io/git-tools/git-console.png)

You can open the Git Changes Windows by click the Git Changes menu under GITTOOLS, and then click the 'Git Console (Beta)' tab.

**Comment by lookforit** [comment]
Got it ，Thanks！
I tried it, it is very  convenient  just like `git bash` embeed in VS .
I think some feathures should be added to make it more useful:
*  `font ` in the console window can be customized 
*  `auto complete ` is more intelligent: support `--`symbol ,eg:
 
``` bash
  git --version 
  ```
    `version `should be poped up after `--`

*  User can input when pop up menu appears, by now input is disableed and  user can only selct the item .

**Comment by yysun** [comment]
Thanks for the suggestions.

Regarding to the comments about the input was disabled when autocomplete
pop up appears. The pop up can be dismissed by the ESC key.
