### ISSUE TITLE
Navigation caret not visible

### ISSUE THREAD

**Issue by bobinush** [yysun/git-tools#33]
Using Visual Studio Professional 2019 with dark theme (or any other theme) the navigation caret not visible in the comment textbox, so it's hard to type messages and navigate through it. 
![image](https://user-images.githubusercontent.com/12391559/67002237-c1b6d680-f0db-11e9-9762-dfcebe1bda1f.png)

**Comment by bobinush** [comment]
The issue was a Visual Studio setting. Tools > Options > Environment > General > disable "Optimize rendering for screens with different pixel densities (requires restart)"

**Comment by yysun** [comment]
Thank you.
