### ISSUE TITLE
Solution Explorer icons

### ISSUE THREAD

**Issue by TeaDrivenDev** [yysun/git-tools#4]
I suppose with the Git provider removed, there is no way to bring back the alternate icon set for Solution Explorer, is there? That was always one the most important features of GitScc, and I'm very sad to see it go. Microsoft's choice of icons completely misses the point, and I was very happy to be able to get sensible icons in Visual Studio.

**Comment by yysun** [comment]
There is a clone of GitScc for VS2015.
https://visualstudiogallery.msdn.microsoft.com/51e11ccc-6334-4873-912d-bf5025eb115d?SRC=VSIDE
