### ISSUE TITLE
VS 2015 gets very slow after a short period of time

### ISSUE THREAD

**Issue by ktw** [yysun/git-tools#8]
My setup:
Core i7 4710mq CPU, 16GB of RAM, SSD disk.
Fresh copy of Visual Studio 2015, working on a solution with 87 C# projects.

The same issue was also present in the 2013 version.

The old plug-in "Git Source Control Provider" worked fine.
(Unfortunately not available for VS2015)

**Comment by yysun** [comment]
There is a clone of GitScc for VS2015.
https://visualstudiogallery.msdn.microsoft.com/51e11ccc-6334-4873-912d-bf5025eb115d

**Comment by ktw** [comment]
Super! Testing it now, and no problems so far.
