### ISSUE TITLE
Margin feature is missing

### ISSUE THREAD

**Issue by cyberium** [yysun/git-tools#9]
Any plan to reintroduce margin feature like  "Git Source Control Provider"?

Get that feature inside the editor is a valuable bonus.

Thank you for your excelent job.

**Comment by yysun** [comment]
You may want to try Git Diff Margin Extension:
https://visualstudiogallery.msdn.microsoft.com/cf49cf30-2ca6-4ea0-b7cc-6a8e0dadc1a8

**Comment by cyberium** [comment]
Thank you very much i wonder how i missed that.
